upstream_package_name: insights-core
downstream_package_name: insights-core
specfile_path: insights-core.spec
release_suffix: "99.{PACKIT_RPMSPEC_RELEASE}"

actions:
  post-upstream-clone:
    - sed -i -e '/cachecontrol/d' -e '/defusedxml/d' -e '/jinja2/d' -e '/lockfile/d' -e '/redis/d' -e '/setuptools;/d' pyproject.toml setup.py
    - sed -i -e '/insights-.*=/d' -e '/mangle =/d' pyproject.toml setup.py
    - sed -i -e 's/^.*$/99.dev/' insights/RELEASE
    - cp insights/tests/filters.yaml insights/filters.yaml
    - cp MANIFEST.in.client.rpm MANIFEST.in
  get-current-version:
    - awk '/^Version:/ {print $2;}' insights-core.spec
  create-archive:
    # - bash -c 'echo ${PACKIT_RPMSPEC_RELEASE}'
    # - bash -c 'sed -i -e "s/^.*$/${PACKIT_RPMSPEC_RELEASE}/" insights/RELEASE'
    - bash -c 'python3 setup.py sdist'
    - bash -c 'ls dist/insights*.tar.*'

jobs:
  - job: copr_build
    trigger: pull_request
    branch: master
    targets:
      - rhel-9-x86_64
      - rhel-9-aarch64
      - rhel-9-s390x
      - rhel-10-x86_64
      - rhel-10-aarch64
      - rhel-10-ppc64le
      - rhel-10-s390x
      - centos-stream-9
      - centos-stream-10
      - fedora-rawhide
      # - rhel-9-ppc64le
