upstream_package_name: insights-core
downstream_package_name: insights-core
specfile_path: insights-core.spec

actions:
  post-upstream-clone:
    - sed -i -e '/cachecontrol/d' -e '/defusedxml/d' -e '/jinja2/d' -e '/lockfile/d' -e '/redis/d' -e '/setuptools;/d' pyproject.toml setup.py
    - sed -i -e '/insights =/d' -e '/insights-dupkey/d' -e '/insights-run/d' -e '/insights-inspect/d' -e '/mangle =/d' pyproject.toml setup.py
    - echo "dev" > insights/RELEASE
    - cp MANIFEST.in.client MANIFEST.in
    # - python3 -m pip3 install build
    # - python3 -m build --sdist
    - python3 setup.py sdist
  get-current-version:
    - awk '/^Version:/ {print $2;}' insights-core.spec
  create-archive:
    - bash -c 'ls dist/insights*.tar.*'
  fix-spec-file:
    - sed -i -e "s/1%{?dist}/dev%{?dist}/g" insights-core.spec

jobs:
  - job: copr_build
    trigger: pull_request
    branch: master
    targets:
      - rhel-9
      - rhel-10
      - centos-stream-10
      - fedora-rawhide
