default_install_hook_types:
- pre-commit
- commit-msg

repos:

- repo: https://github.com/psf/black
  rev: 26.3.1
  hooks:
  - id: black
    args: [--safe, --quiet, --skip-string-normalization, --line-length, "100"]
    require_serial: true


- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    # inherit from original .flake8
    # add news:
    # - W503 black conflicts with "line break before operator" rule
    args: ['--ignore=E126,E127,E128,E203,E501,E722,E741,W503,W504']


- repo: https://github.com/gitleaks/gitleaks
  rev: v8.30.1
  hooks:
  - id: gitleaks


- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.4.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: check-ast
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
