language: python
cache:
  directories:
  - "/home/travis/virtualenv/python2.7.9/"
python:
- '2.7'
install: pip install -e .[develop]
script: ./build.sh
services:
  - docker
sudo: required
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
