[tox]
requires = tox-uv
envlist = unit-py39,unit-py311,unit-py312,unit-py314

[testenv:unit-py39]
basepython = python3.9
usedevelop = true
deps = .[testing]
commands =
    pytest {posargs:--cov --cov-branch --cov-report=}

[testenv:unit-py311]
basepython = python3.11
usedevelop = true
deps = .[testing]
commands =
    pytest {posargs:--cov --cov-branch --cov-report=}

[testenv:unit-py312]
basepython = python3.12
usedevelop = true
deps = .[testing]
commands =
    pytest {posargs:--cov --cov-branch --cov-report=}

[testenv:unit-py314]
basepython = python3.14
usedevelop = true
deps = .[testing]
commands =
    pytest {posargs:--cov --cov-branch --cov-report=}

[testenv:lint]
deps = .[linting]
commands =
    flake8 .

[testenv:docs]
deps = .[docs]
allowlist_externals =
    pandoc
commands =
    sphinx-build -W -b html -qa -E docs docs/_build/html
