allowDisabledDocker: false
apiVersion: v1
dnsDomain: cluster.local
dnsIP: 10.66.208.145
dockerConfig:
  execHandlerName: ""
iptablesSyncPeriod: "30s"
imageConfig:
  format: openshift3/ose-${component}:${version}
  latest: false
kind: NodeConfig
kubeletArguments:
  node-labels: []
masterClientConnectionOverrides:
  acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
  contentType: application/vnd.kubernetes.protobuf
  burst: 200
  qps: 100
masterKubeConfig: system:node:master.ose.com.kubeconfig
networkPluginName: redhat/openshift-ovs-subnet
networkConfig:
   mtu: 1450
   networkPluginName: redhat/openshift-ovs-subnet
nodeName: master.ose.com
podManifestConfig:
servingInfo:
  bindAddress: 0.0.0.0:10250
  certFile: server.crt
  clientCA: ca.crt
  keyFile: server.key
volumeDirectory: /var/lib/origin/openshift.local.volumes
proxyArguments:
  proxy-mode:
     - iptables
volumeConfig:
  localQuota:
    perFSGroup:
