name: Trigger Specs Cross Check Job on gitlab

on:
  push:
    branches: [ master, '3.0']
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Specs Cross Check Job
      uses: actions/checkout@v2
      with:
        url: "https://gitlab.cee.redhat.com/"
        token: GITHUB_CI_TOKEN
        project_id: 61604
